---
- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none
- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
- name: Load required modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - br_netfilter
    - overlay
  become: true
- name: Create the .conf file to load the modules at bootup
  ansible.builtin.template:
    src: kernel_modules.conf.j2
    dest: /etc/modules-load.d/k8s_kernel_modules.conf
  become: true
- name: Modify sysctl entries
  ansible.posix.sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
  ignore_errors: True
  with_items:
    - {key: net.bridge.bridge-nf-call-ip6tables, value: 1}
    - {key: net.bridge.bridge-nf-call-iptables,  value: 1}
    - {key: net.ipv4.ip_forward,  value: 1}
  become: true
- name: Add Docker Repository
  ansible.builtin.get_url:
    url:  https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  become: true
- name: Install containerd.io
  ansible.builtin.package: 
    name: containerd.io
    state: present
    update_cache: yes 
  become: true
- name: Create containerd directory
  ansible.builtin.file: 
    name: /etc/containerd
    state: directory
  become: true 
- name: Check if config.toml is updated
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^#[grpc]'
    state: absent
  check_mode: yes
  changed_when: false
  register: containerd_config
  become: true
- name: Render containerd default config
  ansible.builtin.shell: containerd config default > /etc/containerd/config.toml
  when: 
    - containerd_config.found
  become: true
- name: enable SystemdCgroup for containerd
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: '^(\s*)SystemdCgroup(.*)$'
    replace: '\1SystemdCgroup = true'
  notify:
    - reload containerd
  become: true
- name: start and enable containerd
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: yes
  become: true
- name: Add kubernetes repository
  ansible.builtin.template:
    src: 'kubernetes.repo.j2'
    dest: /etc/yum.repos.d/kubernetes.repo
  become: true
- name: Install kubernetes packages
  yum:
    name: [kubelet,kubeadm,kubectl]
    disable_excludes: kubernetes
  become: true
- name: Enable kubelet service
  ansible.builtin.service:
    name: kubelet
    enabled: yes
  become: true