stages:
  - module-pipelines

ansible:
  stage: module-pipelines
  trigger:
    include:
      - local: 'ansible/ansible.yml'
    strategy: depend
  only:
    - changes:
          - ansible/*
terraform:
  stage: module-pipelines
  trigger:
    include:
      - local: 'terraform/terraform.yml'
    strategy: depend
  only:
    - changes:
          - terraform/*
