---
- name: Add Gitlab runner Repository
  ansible.builtin.get_url:
    url:  https://packages.gitlab.com/install/repositories/runner/gitlab-runner/config_file.repo?os=centos&dist=7&source=script
    dest: /etc/yum.repos.d/runner_gitlab-runner.repo
- name: Add Gitlab runner Repository key
  rpm_key:
    key: https://packages.gitlab.com/runner/gitlab-runner/gpgkey/runner-gitlab-runner-49F16C5CC3A0F81F.pub.gpg
- name: Install Gitlab runner
  ansible.builtin.yum: 
    name: gitlab-runner-16.10.0-1.x86_64
    state: present
    update_cache: yes
- name: Config & lanch gitlab-runner.service
  template:
    src: gitlab-runner.service.j2
    dest: /etc/gitlab-runner/config.toml
  notify:
    - restart gitlab-runner.service
