---
- name: Creates directory
  ansible.builtin.file:
    path: /etc/gitlab-runner
    state: directory
- name: delete file
  ignore_errors: yes
  file:
    state: absent
    path: /etc/gitlab-runner/config.toml
- name: Copy config.toml
  template:
    src: config.toml.j2
    dest: /etc/gitlab-runner/config.toml
- name: run gitlab-runner
  community.docker.docker_container:
    name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    state: started
    recreate: true
    volumes:
      - /etc/gitlab-runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock