stages:
  - deploy

image: alpine/gitlab-ansible-terraform:1.1.9
before_script:
  - export ID_GITLAB_RUNNER=${ID_GITLAB_RUNNER}
  - export NAME_GITLAB_RUNNER=${NAME_GITLAB_RUNNER}
  - export TOKEN_GITLAB_RUNNER=${TOKEN_GITLAB_RUNNER}
  - cd ansible
  - ansible --version
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod -R 600 ~/.ssh
  - export ANSIBLE_FORCE_COLOR=true
deploy:
  stage: deploy
  script:
    - ansible-playbook playbook.yaml -i inventory.yaml
